### ISSUE TITLE
Correct padding for menu item

### ISSUE THREAD

**Issue by peter-gribanov** [anime-db/catalog-bundle#218]
See in [code](https://github.com/anime-db/catalog-bundle/blob/master/src/Resources/public/css/40-navigation.css#L75).
```css
.b-dropdown-menu .icon-label {
    background-position: 10px 12px;
    padding: 0 10px 0 30px;
    /* padding: 0; */
}
```
